### ISSUE TITLE
一行内の文字数及び文字数オーバーの表示の改善案

### ISSUE THREAD

**Issue by wbxshiori** [umaaji298/araisan#5]
- 半角英数字と半角記号（.,/'";:()など）を0.6文字として計算してください。Courier Newの英数字単体は30文字が漢字24文字と同じ長さですから。
-  文字数オーバーが起きた時、最初に何行目に起きたのかを表示してください。修正が捗りますから。

**Comment by umaaji298** [comment]
対応しました。


・半角のみだと40文字(40*0.6=24)入力できます。記号も対応しました。
※一部半角記号(&<>"')はセキュリティリスクがあるため利用できなくしています。
最新の仕様は[こちら](https://github.com/umaaji298/araisan/wiki/%E3%83%95%E3%83%AD%E3%82%A2%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E4%BB%95%E6%A7%98%E6%9B%B8)
・文字数オーバー警告表示に該当行を表示するようにしました。
以下の画像のようになります
  

![修正](https://user-images.githubusercontent.com/48826557/79691536-2aedf100-829b-11ea-9468-631fb25f377f.png)
